export type GameObjectiveContract = {
  id: string;
  label: string;
  description: string;
  type: 'INDICATOR' | 'APPROVAL' | 'TREASURY';
  target: number;
  current: number;
  status: 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';
};
export type GameProjectContract = {
  id: string;
  name: string;
  area: string;
  totalCost: number;
  dailyExecutionCost?: number;
  maintenanceCost?: number;
  dailyIndicatorEffects?: Record<string, number>;
  dailyGroupEffects?: Record<string, number>;
  daysTotal: number;
  daysCompleted: number;
  status: 'IN_PROGRESS' | 'COMPLETED';
  risk?: 'NORMAL' | 'DELAYED';
  priorityMode?: 'NORMAL' | 'PRIORITARIA';
  maintenanceMode?: 'NORMAL' | 'REDUZIDA' | 'ADIADA';
};
export type ElectionCandidateContract = { id: string; name: string; isIncumbent: boolean; support: number; rejection: number; platform: string; style: string };
export type ElectionPollContract = { period: string; candidates: { id: string; name: string; support: number; rejection: number }[]; undecided: number };
export type ElectionStateContract = {
  phase: 'PRE_CAMPAIGN' | 'CAMPAIGN' | 'DEBATE' | 'RESULT';
  week: number;
  candidates: ElectionCandidateContract[];
  incumbentAgenda: string[];
  debateCompleted: boolean;
  winnerId?: string;
  explanation?: string;
  history: { type: 'CAMPAIGN' | 'DEBATE' | 'RESULT'; week: number; label: string; incumbentSupport: number; cost?: number }[];
  pollHistory: ElectionPollContract[];
  campaignFunds: number;
  promises: { id: string; area: string; label: string; estimatedCost: number; deadlineWeeks: number; credibility: number; groupEffects: Record<string, number> }[];
  debateQuestion: string;
};
export type GameEffectsContract = Record<string, number> & Partial<{
  health: number;
  approval: number;
  education: number;
  infrastructure: number;
  transport: number;
  security: number;
}>;
export type GameViewContract = {
  id: string;
  mayorName: string;
  cityName: string;
  currentDate: string;
  mandateEndDate: string;
  evaluationDate?: string;
  daysRemaining: number;
  activeFocus?: string;
  focusDaysRemaining?: number;
  focusMetric?: 'treasury' | 'capacity' | 'service' | 'social';
  focusBaseline?: number;
  population: number;
  populationTrend?: number;
  treasury: number;
  debt: number;
  approval: number;
  indicators: { key: string; label: string; value: number; trend: number }[];
  decisions: {
    id: string;
    parentDecisionId?: string;
    title: string;
    context: string;
    status: 'PENDING' | 'RESOLVED';
    chosenOptionId?: string;
    resolvedDate?: string;
    options: { id: string; label: string; description?: string; groupEffects?: Record<string, number> }[];
  }[];
  effects?: GameEffectsContract;
  activeEffects?: Record<string, number>;
  activeGroupEffects?: Record<string, number>;
  budgetPressureDays?: Record<string, number>;
  groups?: {
    key: string;
    label: string;
    satisfaction: number;
    reputation?: number;
    concern: string;
    populationWeight?: number;
  }[];
  secretaries?: {
    key: string;
    label: string;
    efficiency: number;
    pressure: number;
  }[];
  budget?: { key: string; label: string; dailyCost: number }[];
  projects?: GameProjectContract[];
  objectives?: GameObjectiveContract[];
  news?: string[];
  history?: string[];
  legacy?: string[];
  evaluation?: Record<string, unknown>;
  fiscalAlert?: string;
  fiscalStability?: number;
  revenueSources?: { ownTaxes: number; commerce: number; transfers: number };
  economicPolicies?: { commerceIncentive: number; taxModernization: number };
  administrativeCapacity?: number;
  portfolioStatus?: 'SAUDAVEL' | 'PRESSIONADO' | 'SOBRECARREGADO';
  administrativeAlerts?: string[];
  secretaryRecoveryDays?: Record<string, number>;
  causalLinks?: { date: string; decisionId?: string; cause: string; effect: string; signal: string; observedEffect?: string; affectedGroups?: string[]; groupEffects?: Record<string, number>; objectiveIds?: string[] }[];
  ledger?: {
    date: string;
    label: string;
    amount: number;
    kind: 'INCOME' | 'EXPENSE';
    category?: 'OPERATION' | 'DECISION' | 'REVENUE' | 'PROJECT';
  }[];
  snapshots?: {
    date: string;
    approval: number;
    treasury: number;
    serviceQuality: number;
    population?: number;
    administrativeEfficiency?: number;
    fiscalStability?: number;
    socialTrust?: number;
  }[];
  electionState?: ElectionStateContract | Record<string, unknown>;
};
